-- MySQL Script generated by MySQL Workbench
-- 11/15/16 21:16:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gc` DEFAULT CHARACTER SET latin1 ;
USE `gc` ;

-- -----------------------------------------------------
-- Table `gc`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gc`.`curso` ;

CREATE TABLE IF NOT EXISTS `gc`.`curso` (
  `COD_CURSO` INT(11) NOT NULL AUTO_INCREMENT,
  `NOM_CURSO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`COD_CURSO`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `curso_i01` ON `gc`.`curso` (`NOM_CURSO` ASC);


-- -----------------------------------------------------
-- Table `gc`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gc`.`aluno` ;

CREATE TABLE IF NOT EXISTS `gc`.`aluno` (
  `COD_ALUNO` INT(11) NOT NULL AUTO_INCREMENT,
  `COD_CURSO` INT(11) NOT NULL,
  `NUM_RA` VARCHAR(10) NOT NULL,
  `NOM_ALUNO` VARCHAR(100) NOT NULL,
  `NUM_CPF_ALUNO` VARCHAR(25) NOT NULL,
  `DES_EMAIL` VARCHAR(100) NULL,
  `IND_DEFICIENTE` CHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`COD_ALUNO`),
  CONSTRAINT `fk_aluno_curso`
    FOREIGN KEY (`COD_CURSO`)
    REFERENCES `gc`.`curso` (`COD_CURSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `aluno_i01` ON `gc`.`aluno` (`COD_CURSO` ASC);

CREATE INDEX `aluno_i02` ON `gc`.`aluno` (`NUM_RA` ASC);

CREATE INDEX `aluno_i03` ON `gc`.`aluno` (`NOM_ALUNO` ASC);

CREATE INDEX `aluno_i04` ON `gc`.`aluno` (`NUM_CPF_ALUNO` ASC);

CREATE INDEX `aluno_i05` ON `gc`.`aluno` (`DES_EMAIL` ASC);


-- -----------------------------------------------------
-- Table `gc`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gc`.`empresa` ;

CREATE TABLE IF NOT EXISTS `gc`.`empresa` (
  `COD_EMPRESA` INT(11) NOT NULL AUTO_INCREMENT,
  `NOM_EMPRESA` VARCHAR(200) NOT NULL,
  `NUM_CNPJ` VARCHAR(20) NULL,
  `DES_ENDERECO` VARCHAR(200) NULL,
  `NOM_BAIRRO` VARCHAR(100) NULL,
  `NUM_CEP` VARCHAR(20) NULL,
  `NOM_CIDADE` VARCHAR(100) NULL,
  `DES_UF` VARCHAR(2) NULL,
  `DES_EMAIL` VARCHAR(100) NULL,
  `NUM_TELEFONE` VARCHAR(200) NULL,
  `NOM_CONTATO` VARCHAR(100) NULL,
  `DES_OBSERVACAO` VARCHAR(4000) NULL,
  PRIMARY KEY (`COD_EMPRESA`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `empresa_i01` ON `gc`.`empresa` (`NOM_EMPRESA` ASC);

CREATE UNIQUE INDEX `empresa_i02` ON `gc`.`empresa` (`NUM_CNPJ` ASC);


-- -----------------------------------------------------
-- Table `gc`.`contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gc`.`contrato` ;

CREATE TABLE IF NOT EXISTS `gc`.`contrato` (
  `COD_CONTRATO` INT(11) NOT NULL AUTO_INCREMENT,
  `COD_ALUNO` INT(11) NOT NULL,
  `COD_EMPRESA` INT(11) NOT NULL,
  `COD_CONTRATO_TIPO` INT(11) NOT NULL,
  `COD_CONTRATO_SITUACAO_ATUAL` INT(11) NOT NULL,
  `NUM_PROTOCOLO` VARCHAR(20) NULL,
  `DAT_ENTRADA` DATE NULL,
  `DAT_INICIO_ATUAL` DATE NULL,
  `DAT_TERMINO_ATUAL` DATE NULL,
  `DAT_RESCISAO` DATE NULL,
  `VAL_BOLSA` DECIMAL(20,2) NULL,
  `VAL_AUXILIO_TRANSPORTE` DECIMAL(20,2) NULL,
  `QTD_CARGA_HORARIA_DIARIA` DECIMAL(10,2) NULL,
  `QTD_CARGA_HORARIA_SEMANAL` DECIMAL(10,2) NULL,
  `DES_OBSERVACAO` VARCHAR(4000) NULL,
  `IND_ALUNO_CONTRATADO` CHAR(1) NULL,
  PRIMARY KEY (`COD_CONTRATO`),
  CONSTRAINT `fk_aluno_contrato`
    FOREIGN KEY (`COD_ALUNO`)
    REFERENCES `gc`.`aluno` (`COD_ALUNO`),
  CONSTRAINT `fk_empresa_contrato`
    FOREIGN KEY (`COD_EMPRESA`)
    REFERENCES `gc`.`empresa` (`COD_EMPRESA`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `contrato_i01` ON `gc`.`contrato` (`COD_ALUNO` ASC);

CREATE INDEX `contrato_i02` ON `gc`.`contrato` (`COD_EMPRESA` ASC);

CREATE UNIQUE INDEX `contrato_i03` ON `gc`.`contrato` (`NUM_PROTOCOLO` ASC);


-- -----------------------------------------------------
-- Table `gc`.`contrato_situacao_historico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gc`.`contrato_situacao_historico` ;

CREATE TABLE IF NOT EXISTS `gc`.`contrato_situacao_historico` (
  `COD_CONTRATO_SITUACAO_HISTORICO` INT(11) NOT NULL AUTO_INCREMENT,
  `COD_CONTRATO` INT(11) NOT NULL,
  `COD_CONTRATO_SITUACAO` INT(11) NOT NULL,
  `DAT_SITUACAO` DATE NULL,
  `DES_OBSERVACAO` VARCHAR(4000) NULL,
  PRIMARY KEY (`COD_CONTRATO_SITUACAO_HISTORICO`),
  CONSTRAINT `fk_contrato_contrato_situacao_historico`
    FOREIGN KEY (`COD_CONTRATO`)
    REFERENCES `gc`.`contrato` (`COD_CONTRATO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `contrato_situacao_historico_i01` ON `gc`.`contrato_situacao_historico` (`COD_CONTRATO` ASC);


-- -----------------------------------------------------
-- Table `gc`.`contrato_termo_aditivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gc`.`contrato_termo_aditivo` ;

CREATE TABLE IF NOT EXISTS `gc`.`contrato_termo_aditivo` (
  `COD_TERMO_ADITIVO` INT(11) NOT NULL AUTO_INCREMENT,
  `COD_CONTRATO` INT(11) NOT NULL,
  `DAT_TERMO_ADITIVO` DATE NULL DEFAULT NULL,
  `DES_OBSERVACAO` VARCHAR(4000) NULL DEFAULT NULL,
  `DAT_INICIO_HISTORICO` DATE NULL DEFAULT NULL,
  `DAT_TERMINO_HISTORICO` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`COD_TERMO_ADITIVO`),
  CONSTRAINT `FK_FK_CONTRATO_CONTRATO_TERMO_ADITIVO`
    FOREIGN KEY (`COD_CONTRATO`)
    REFERENCES `gc`.`contrato` (`COD_CONTRATO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `contrato_termo_aditivo_i01` ON `gc`.`contrato_termo_aditivo` (`COD_CONTRATO` ASC);


-- -----------------------------------------------------
-- Table `gc`.`convenio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gc`.`convenio` ;

CREATE TABLE IF NOT EXISTS `gc`.`convenio` (
  `COD_CONVENIO` INT(11) NOT NULL AUTO_INCREMENT,
  `COD_EMPRESA` INT(11) NOT NULL,
  `COD_CURSO` INT(11) NOT NULL,
  `COD_CONVENIO_SITUACAO` INT(11) NOT NULL,
  `DAT_VENCIMENTO` DATE NULL,
  `DAT_ASSINATURA` DATE NULL,
  PRIMARY KEY (`COD_CONVENIO`),
  CONSTRAINT `fk_empresa_convenio`
    FOREIGN KEY (`COD_EMPRESA`)
    REFERENCES `gc`.`empresa` (`COD_EMPRESA`),
  CONSTRAINT `fk_convenio_curso`
    FOREIGN KEY (`COD_CURSO`)
    REFERENCES `gc`.`curso` (`COD_CURSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `convenio_i01` ON `gc`.`convenio` (`COD_EMPRESA` ASC);

CREATE INDEX `convenio_i02` ON `gc`.`convenio` (`COD_CURSO` ASC);


-- -----------------------------------------------------
-- Table `gc`.`documento_digitalizado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gc`.`documento_digitalizado` ;

CREATE TABLE IF NOT EXISTS `gc`.`documento_digitalizado` (
  `COD_DOCUMENTO_DIGITALIZADO` INT(11) NOT NULL AUTO_INCREMENT,
  `COD_CONTRATO` INT(11) NOT NULL,
  `COD_TERMO_ADITIVO` INT(11) NULL,
  `IMG_DOCUMENTO` LONGBLOB NOT NULL,
  `NOM_DOCUMENTO` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`COD_DOCUMENTO_DIGITALIZADO`),
  CONSTRAINT `fk_contrato_documento_digitalizado`
    FOREIGN KEY (`COD_CONTRATO`)
    REFERENCES `gc`.`contrato` (`COD_CONTRATO`),
  CONSTRAINT `fk_contrato_termo_aditivo_documento_difitalizado`
    FOREIGN KEY (`COD_TERMO_ADITIVO`)
    REFERENCES `gc`.`contrato_termo_aditivo` (`COD_TERMO_ADITIVO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `documento_digitalizado_i01` ON `gc`.`documento_digitalizado` (`COD_CONTRATO` ASC);

CREATE INDEX `documento_digitalizado_02` ON `gc`.`documento_digitalizado` (`COD_TERMO_ADITIVO` ASC);


-- -----------------------------------------------------
-- Table `gc`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gc`.`usuario` ;

CREATE TABLE IF NOT EXISTS `gc`.`usuario` (
  `COD_USUARIO` INT(11) NOT NULL AUTO_INCREMENT,
  `NOM_USUARIO` VARCHAR(100) NOT NULL,
  `DES_LOGIN` VARCHAR(50) NOT NULL,
  `COD_SENHA` VARCHAR(100) NOT NULL,
  `DES_EMAIL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`COD_USUARIO`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `usuario_i01` ON `gc`.`usuario` (`NOM_USUARIO` ASC);

CREATE INDEX `usuario_i02` ON `gc`.`usuario` (`DES_LOGIN` ASC);

CREATE INDEX `usuario_i03` ON `gc`.`usuario` (`DES_EMAIL` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;