/* ALUNO */
INSERT INTO `aluno` (`COD_ALUNO`, `COD_CURSO`, `NUM_RA`, `NOM_ALUNO`, `NUM_CPF_ALUNO`, `DES_EMAIL`, `IND_DEFICIENTE`) VALUES ('1', '10', '11223344', 'Aluno Teste', '11111111111', 'aluno@newtonpaiva.br', 'N');
INSERT INTO `aluno` (`COD_ALUNO`, `COD_CURSO`, `NUM_RA`, `NOM_ALUNO`, `NUM_CPF_ALUNO`, `DES_EMAIL`, `IND_DEFICIENTE`) VALUES ('2', '1', '22334455', 'Aluno Deficiente', '22222222222', 'aluno.def@newtonpaiva.br', 'S');

/* USUARIO */
INSERT INTO `usuario` (`COD_USUARIO`,`NOM_USUARIO`,`DES_LOGIN`,`COD_SENHA`,`DES_EMAIL`) VALUES (1,'Administrador','admin','123','admin@newtonpaiva.br');

/* EMPRESA */
INSERT INTO `empresa` (`COD_EMPRESA`, `NOM_EMPRESA`, `NUM_CNPJ`, `DES_ENDERECO`, `NOM_BAIRRO`, `NUM_CEP`, `NOM_CIDADE`, `DES_UF`) VALUES (1, 'Newton Paiva', '16521155000103', 'R Jose Claudio Rezende, 420', 'Estoril', '30494230', 'Belo Horizonte', 'MG');

/* CONTRATO */
INSERT INTO contrato (`COD_CONTRATO`, `COD_ALUNO`, `COD_EMPRESA`, `COD_CONTRATO_TIPO`, `COD_CONTRATO_SITUACAO_ATUAL`, `NUM_PROTOCOLO`, `DAT_ENTRADA`, `DAT_INICIO_ATUAL`, `QTD_CARGA_HORARIA_DIARIA`, `QTD_CARGA_HORARIA_SEMANAL`, `DES_OBSERVACAO`) VALUES ('1', '1', '1', '0', '0', '123456', '2016-10-01', '2016-10-05', '4', '40', 'Teste');